# Generated by Django 4.2.5 on 2024-04-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderitem_owner_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Cart'), (1, 'Confirmed'), (2, 'Processing'), (3, 'Processed'), (4, 'Delivered'), (5, 'Rejected')], default=0),
        ),
    ]
