# Generated by Django 4.2.5 on 2024-04-19 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_collection_rename_prioriy_product_priority_and_more'),
        ('orders', '0005_rename_order_orderitem_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(2, 'ORDER_PROCESSING'), (2, 'ORDER_PROCESSED'), (4, 'ORDER_DELIVERED'), (5, 'ORDER_REJECTED')], default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_carts', to='products.product'),
        ),
    ]
