# Generated by Django 4.2.5 on 2024-03-22 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=100)),
                ('cover_img', models.ImageField(upload_to='collection_covers/')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prioriy',
            new_name='priority',
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirts', to='products.collection'),
        ),
    ]
